/*
 * ProTK High Performance Support Script
 * 
 * Fast generation of ARFFs from Praat's Formant(sl) function
 * and boundary files generated by ProTK
 */
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <stdlib.h>
#include <gsl/gsl_statistics_double.h>

#define FORMANT_FRAME_SIZE 0.00625
#define ANALYSIS_FRAME_SIZE 0.02
#define ANALYSIS_WINDOW_SIZE 0.01

typedef struct formants_t {
    double f1;
    double f2;
    double f1_f2;
} FORMANTS;

typedef struct formants_stats_t {
    double start;
    double end;
    FORMANTS mean;
    FORMANTS stdev;
    FORMANTS median;
} FORMANTS_STATS;

typedef struct bounds_t {
    double start;
    double end;
    double duration;
    int pred;
    int succ;
    int truth;
} BOUNDS;

typedef struct row_t {
    FORMANTS_STATS s;
    BOUNDS b;
} ROW;

int cmp(const void *x, const void *y)
{
    double xx = *(double*)x, yy = *(double*)y;
    if (xx < yy) return -1;
    if (xx > yy) return  1;
    return 0;
}

int main(int argc, char** argv) {
    if(argc < 3) {
        printf("Usage: formantsl <praat formant file> <protk boundary file>");
        exit(0);
    }
    const char *mode = "r";
    FILE *f = fopen(argv[1],mode);
    FILE *fb = fopen(argv[2],mode);

    struct stat s;
    int result = stat(argv[1], &s);
    char fbuf[s.st_size];
    result = fread(fbuf, 1, s.st_size, f);

    result = stat(argv[2], &s);
    //char boundbuf[s.st_size];
    char* boundbuf = malloc(s.st_size);
    result = fread(boundbuf, 1, s.st_size, fb);

    //printf("---HEADER---\n");
    strtok(fbuf, "\n");
    int i;
    int j;
    int fmtcount = 0;
    for(i = 0; i < 7; i++) {
        char* hline = strtok(NULL,"\n");
        if(i == 3) sscanf(hline,"%ld",&fmtcount);
        //else printf("%s\n",hline);
    }
    //printf("---END HEADER---\n");

    //printf("\nReading %d formants...\n", fmtcount);

    char* buf;
    int val = 0;
    int fmtidx = 0;
    double fmts[fmtcount][6];
    int fmtct = 0;

    buf = strtok(NULL,"\n");

    while(buf != NULL) {
        double fmt = 0.0;
        if(val%2 == 0) {
            sscanf(buf, "%lf", &fmt);
            fmts[fmtct][fmtidx] = fmt;
            fmtidx++;
        }
        if((val+1)%12 == 0) {
            fmtidx = 0;
            fmtct++;
        }
        val++;
        buf = strtok(NULL,"\n");
    }
    
    FORMANTS formants[fmtcount];
    for(i = 0; i < fmtcount; i++) {
        formants[i].f1 = fmts[i][1];
        formants[i].f2 = fmts[i][2];
        formants[i].f1_f2 = fmts[i][1] / fmts[i][2];
    }

    double frame_x = 0.0;
    int low_idx;
    int high_idx;
    int fsize;
    int max_count = 5788 / (int)((ANALYSIS_WINDOW_SIZE / 0.00625));
    FORMANTS_STATS stats[max_count];
    int ct = 0;
    while(1) {
        frame_x += ANALYSIS_WINDOW_SIZE;
        if((frame_x / 0.00625) > fmtcount) {
            frame_x -= ANALYSIS_WINDOW_SIZE;
            //printf("Last window at %f (%f)\n", frame_x, 0.00625);
            break;
        }
        low_idx = (int)(frame_x / 0.00625);
        high_idx = (int)((frame_x+ANALYSIS_FRAME_SIZE) / 0.00625);
        if(high_idx >= fmtcount) break;
        fsize = high_idx-low_idx;
        //printf("%d\n", fsize);

        double* start = (double*)&formants[low_idx];
        double mean_f1 = gsl_stats_mean(start, 3, fsize);
        start++;
        double mean_f2 = gsl_stats_mean(start, 3, fsize);
        start++;
        double mean_f1_f2 = gsl_stats_mean(start, 3, fsize);
        //printf("%f,%f,%f\n", mean_f1, mean_f2, mean_f1_f2);
        
        stats[ct].mean.f1 = mean_f1;
        stats[ct].mean.f2 = mean_f2;
        stats[ct].mean.f1_f2 = mean_f1_f2;

        start -= 2;
        double sd_f1 = gsl_stats_sd_m(start, 3, fsize, mean_f1);
        start++;
        double sd_f2 = gsl_stats_sd_m(start, 3, fsize, mean_f2);
        start++;
        double sd_f1_f2 = gsl_stats_sd_m(start, 3, fsize, mean_f1_f2);
        //printf("%f,%f,%f\n", sd_f1, sd_f2, sd_f1_f2);
        
        stats[ct].stdev.f1 = sd_f1;
        stats[ct].stdev.f2 = sd_f2;
        stats[ct].stdev.f1_f2 = sd_f1_f2;

        start -= 2;
        double sort[fsize];
        for(i = 0; i < fsize; i++) sort[i] = start[3*i];
        qsort(sort, fsize, sizeof(double), cmp);
        double median_f1 = gsl_stats_median_from_sorted_data(sort, 1, fsize);
        start++;
        for(i = 0; i < fsize; i++) sort[i] = start[3*i];
        qsort(sort, fsize, sizeof(double), cmp);
        double median_f2 = gsl_stats_median_from_sorted_data(sort, 1, fsize);
        start++;
        for(i = 0; i < fsize; i++) sort[i] = start[3*i];
        qsort(sort, fsize, sizeof(double), cmp);
        double median_f1_f2 = gsl_stats_median_from_sorted_data(sort, 1, fsize);
        //printf("%f,%f,%f\n", median_f1, median_f2, median_f1_f2);
        
        stats[ct].median.f1 = median_f1;
        stats[ct].median.f2 = median_f2;
        stats[ct].median.f1_f2 = median_f1_f2;

        ct++;
    }

    for(i = 0; i < ct; i++) {
        //printf("F1 mean: %f, F2 mean: %f\n", stats[i].mean.f1, stats[i].mean.f2);
    }
    
    buf = strtok(boundbuf, "\n");
    //printf("blah");
    int boundcount;
    sscanf(buf, "%d", &boundcount);
    //printf("%d", &boundcount);
    BOUNDS bounds[boundcount];
    for(i = 0; i < boundcount; i++) {
        buf = strtok(NULL, "\n");
        sscanf(buf, "%lf %lf %lf %d %d %d", &bounds[i].start, &bounds[i].end, &bounds[i].duration, &bounds[i].pred, &bounds[i].succ, &bounds[i].truth);
        //printf("%lf %lf %lf %d %d %d\n", bounds[i].start, bounds[i].end, bounds[i].duration, bounds[i].pred, bounds[i].succ, bounds[i].truth);
    }
    /*
    //printf("@RELATION filledpause\n");
    //printf("@ATTRIBUTE f1_mean NUMERIC\n");
    //printf("@ATTRIBUTE f1_stdev NUMERIC\n");
    //printf("@ATTRIBUTE f1_median NUMERIC\n");
    //printf("@ATTRIBUTE f2_mean NUMERIC\n");
    //printf("@ATTRIBUTE f2_stdev NUMERIC\n");
    //printf("@ATTRIBUTE f2_median NUMERIC\n");
    //printf("@ATTRIBUTE f1_f2_mean NUMERIC\n");
    //printf("@ATTRIBUTE f1_f2_stdev NUMERIC\n");
    //printf("@ATTRIBUTE f1_f2_median NUMERIC\n");
    //printf("@ATTRIBUTE word_duration NUMERIC\n");
    //printf("@ATTRIBUTE word_pred_sil {YES,NO}\n");
    //printf("@ATTRIBUTE word_succ_sil {YES,NO}\n");
    //printf("@ATTRIBUTE truth {YES,NO}\n");
    //printf("@DATA\n");*/

    double normal_mean_f1;
    double normal_mean_f2;
    double mean_count;

    int bct = 0; 
    BOUNDS currentBound = bounds[0];
    ROW results[max_count];
    int result_count = 0;
    char* yes = "YES";
    char* no = "NO";

    for(i = 0; i < ct; i++) {
        if(i * ANALYSIS_WINDOW_SIZE > currentBound.end) {
            bct++;
            currentBound = bounds[bct];
        }
        if(i * ANALYSIS_WINDOW_SIZE > currentBound.start) {
            FORMANTS_STATS sts = stats[i];
            normal_mean_f1 += sts.mean.f1;
            normal_mean_f2 += sts.mean.f2;
            mean_count += 1.0;
            results[result_count].s = sts;
            results[result_count].b = currentBound;
            result_count++;
        }
    }
    
    normal_mean_f1 /= mean_count;
    normal_mean_f2 /= mean_count;

    for(i = 0; i < result_count; i++) {
        FORMANTS_STATS sts = results[i].s;
        currentBound = results[i].b;
#ifndef RUNTEST
        printf("%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%s,%s,%s\n",
            sts.mean.f1 - normal_mean_f1, sts.stdev.f1, sts.median.f1,
            sts.mean.f2 - normal_mean_f2, sts.stdev.f2, sts.median.f2,
            sts.mean.f1_f2, sts.stdev.f1_f2, sts.median.f1_f2,
            currentBound.duration, ((currentBound.pred)?yes:no),
            ((currentBound.succ)?yes:no), ((currentBound.truth)?yes:no)); 
#endif
#ifdef RUNTEST
        printf("%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%s,%s,%s\n",
            sts.mean.f1 - normal_mean_f1, sts.stdev.f1, sts.median.f1,
            sts.mean.f2 - normal_mean_f2, sts.stdev.f2, sts.median.f2,
            sts.mean.f1_f2, sts.stdev.f1_f2, sts.median.f1_f2,
            currentBound.duration, ((currentBound.pred)?yes:no),
            ((currentBound.succ)?yes:no), no); 
#endif
    }
    return 0;
}
